'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
type CartItem = { id: string; quantity: number; product: { id: string; name: string; images: string[]; salePrice: number }; option: { id: string; name: string; price: number } | null };
export default function CartPage() {
  const router = useRouter(); const [items, setItems] = useState<CartItem[]>([]); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { const response = await fetch('/api/cart'); if (response.status === 401) { router.push('/auth/login?redirect=/cart'); return; } const data = await response.json(); if (!response.ok) setError(data.error || '장바구니를 불러오지 못했습니다.'); else { setItems(data.data || []); setSelected((data.data || []).map((item: CartItem) => item.id)); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const total = useMemo(() => items.filter((item) => selected.includes(item.id)).reduce((sum, item) => sum + (item.product.salePrice + (item.option?.price || 0)) * item.quantity, 0), [items, selected]);
  const update = async (id: string, quantity: number) => { if (quantity < 1) return; await fetch('/api/cart', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, quantity }) }); await load(); };
  const remove = async (id: string) => { await fetch(`/api/cart?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); await load(); };
  const checkout = () => { if (!selected.length) { setError('구매할 상품을 선택해주세요.'); return; } sessionStorage.setItem('checkoutItems', JSON.stringify(selected)); router.push('/checkout'); };
  return <main className="min-h-screen bg-gradient-to-br from-white via-blue-50/30 to-purple-50/20 px-6 py-12 pb-[110px]"><div className="mx-auto max-w-4xl"><div className="mb-8 flex items-center justify-between"><div><Link href="/products" className="text-sm text-blue-600">← 상품으로</Link><h1 className="mt-2 text-4xl font-bold text-gray-900">장바구니</h1></div><Link href="/" className="font-bold text-gray-900">화니 OTT</Link></div>{loading ? <p className="rounded-2xl bg-white p-8 text-center text-gray-500">불러오는 중...</p> : error && !items.length ? <p className="rounded-2xl bg-white p-8 text-center text-red-500">{error}</p> : <><div className="space-y-3">{items.map((item) => <div key={item.id} className="flex items-center gap-4 rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} className="h-5 w-5" />{item.product.images[0] ? <img src={item.product.images[0]} alt="" className="h-20 w-20 rounded-xl object-cover" /> : <div className="h-20 w-20 rounded-xl bg-gray-100" />}<div className="min-w-0 flex-1"><h2 className="font-semibold text-gray-900">{item.product.name}</h2><p className="text-sm text-gray-500">{item.option?.name || '기본 옵션'}</p><p className="mt-1 font-bold text-blue-600">{(item.product.salePrice + (item.option?.price || 0)).toLocaleString()}원</p></div><div className="flex items-center gap-2"><button onClick={() => void update(item.id, item.quantity - 1)} disabled={item.quantity <= 1} className="h-11 w-11 rounded-lg bg-gray-100 whitespace-nowrap">−</button><span>{item.quantity}</span><button onClick={() => void update(item.id, item.quantity + 1)} className="h-11 w-11 rounded-lg bg-gray-100 whitespace-nowrap">＋</button></div><button onClick={() => void remove(item.id)} className="px-2 py-1 text-sm text-red-500 whitespace-nowrap shrink-0">삭제</button></div>)}</div>{!items.length && <div className="rounded-2xl bg-white p-12 text-center text-gray-500">장바구니가 비어 있습니다.<br /><Link href="/products" className="mt-4 inline-block font-semibold text-blue-600 whitespace-nowrap">상품 보러가기</Link></div>}{!!items.length && <div className="mt-6 flex items-center justify-between rounded-2xl bg-gray-900 p-6 text-white"><div><p className="text-sm text-gray-400">선택 상품 합계</p><p className="text-2xl font-bold">{total.toLocaleString()}원</p></div><button onClick={checkout} className="rounded-xl bg-blue-600 px-6 py-3 font-semibold hover:bg-blue-500 whitespace-nowrap shrink-0">구매 진행</button></div>}</>}</div></main>;
}
